In [1]:
# NumPy 기본 개념 정리
# Numerical Python을 의미하는 NumPy는 Python에서 선형대수 기반의
# 프로그램을 쉽게 만들 수 있도록 지원하는 패키지임

In [2]:
# NumPy 실행하기

import numpy as np

In [3]:
# NumPy의 기반 데이터 타입은 ndarray임
# ndarray를 이용해 NumPy에서 다차원 배열(Multi-dimension)을 쉽게 생성 및 다양한 연산 가능
# NumPy array() 함수는 Python의 list와 같은 다양한 인자를 입력 받아서 ndarray로 변환함
# 생성된 ndarry 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 tupple 형태로
# 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음

array1 = np.array([1, 3, 5])
print('array1 type',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 3, 5],
                   [2, 4, 6]])
print('array2 type',type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 3, 5]])
print('array3 type',type(array3))
print('array3 array 형태:', array3.shape)

array1 type <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
# ndarray.shape는 ndarray의 차원과 크기를 tupple 형태로 나타냄
# array1과 array3의 차이를 이해해야함
# array1은 1차원 array로 3개의 데이터를 가지고 있는 것을 뜻함
# array3은 2차원 array로 1개 row와 3개 column으로 구성되어 1*3=3개의 데이터를 가지고 있는 것을 뜻함

print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


In [5]:
# ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값 등 모두 가능함
# ndarray 내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능함
# 리스트 자료형인 list1은 integer 숫자인 1,3,5를 값으로 가지고 있고
# ndarray로 쉽게 변경할 수 있으며 이렇게 변경된 ndarray 내의 데이터 값은 모두 int32형임 

list1 = [1, 3, 5]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 3 5] int32


In [6]:
# 서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은
# 연산의 특성상 같은 데이터 타입만 가능함
# 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 변환 일괄 적용됨

list2 = [1, 2 , 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [7]:
# ndarray 내 데이터값의 타입 변경은 astype()을 이용해 할 수 있음
# 대용량 데이터의 ndarray를 만들 때 메모리 절약을 해야할 때 보통 이용됨

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
# ndarray 편리하게 생성하기 - 1
# arange()는 0부터 함수 인자 값 -1까지의 값으로 순차적 구성된 1차원 ndarray의 데이터값으로 변환해줌
# defaulf 함수 인자는 stop 값이고, start 값을 부여해 0이 아닌 값으로 시작하는 연속 값을 부여할 수 있음

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
# ndarray 편리하게 생성하기 - 2
# zeros()는 함수 인자로 tupple 형태의 shape 값을 입력하면
# 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환함
# dtype의 default는 float64 형의 데이터임

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [10]:
# ndarray 편리하게 생성하기 - 3
# ones()는 함수 인자로 tupple 형태의 shape 값을 입력하면
# 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환함
# dtype의 default는 float64 형의 데이터임

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
# ndarray 편리하게 생성하기 - 4
# full()은 함수 인자로 tupple 형태의 shape 값과
# 특정 상수를 입력하면 모든 값이 특정 상수로 채운
# 해당 shape를 가진 ndarray를 반환함
# dtype의 default는 None임(특정 상수의 type에 따라감)

full_array = np.full((3,2),7)
print(full_array)
print(full_array.dtype, full_array.shape)

[[7 7]
 [7 7]
 [7 7]]
int32 (3, 2)


In [12]:
# ndarray 편리하게 생성하기 - 5
# eye()는 함수 인자 값 N을 입력하면 NxN 단위행렬을 생성함
# dtype의 default는 float64 형의 데이터임

eye_array = np.eye(3)
print(eye_array)
print(eye_array.dtype, eye_array.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64 (3, 3)


In [13]:
# ndarray 편리하게 생성하기 - 6
# random.random()는 함수 인자로 tupple 형태의 shape 값을 입력하면
# 모든 값을 임의의 값으로 채운 해당 shape를 가진 ndarray를 반환함

random_array = np.random.random((3,3))
print(random_array)
print(random_array.dtype, random_array.shape)

[[0.57811335 0.20613938 0.66034452]
 [0.58004577 0.4670773  0.65969509]
 [0.84233073 0.69631623 0.98138744]]
float64 (3, 3)


In [14]:
# ndarray의 차원과 크기를 변경하는 reshape()
# reshape()는 ndarray를 특정 차원 및 크기로 변환함
# 변환을 원하는 크기를 함수 인자로 부여하면 됨

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
# reshape()를 더 효율적으로 사용하는 방법
# 함수 인자로 -1을 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환함

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # array1과 호환되는 2차원 ndarray로 변환하되, 고정된 5개 column에 맞는 row를 자동으로 생성해 변환함
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1) # array1과 호환되는 2차원 ndarray로 변환하되, 고정된 5개 row에 맞는 column를 자동으로 생성해 변환함
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [16]:
# 배열 인덱싱

a = np.arange(1,13).reshape(3,4)
print(a)

# 슬라이싱을 이용하여 1,2행과 2,3열로 이루어진 부분배열을 만듦
# b는 shape가 (2,2)인 배열이 됨

b = a[:2, 1:3]
print(b)

print(a[1,2]) # a[1,2]와 b[1,1]은 같은 같은 데이터임
print(b[1,1])

# 슬라이싱 된 배열은 원본 배열과 같은 데이터를 참조함
# 즉, 슬라이싱 된 배열을 수정하면 원본 배열 역시 수정됨

b[1,1] = 93
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
7
7
[[ 1  2  3  4]
 [ 5  6 93  8]
 [ 9 10 11 12]]
